### PR TITLE
Ensure the number of router replicas matche the number of infra nodes

### PR DESCRIPTION
**Pull request by fahlmant**
https://issues.redhat.com/browse/OSD-8028

After the IngressController CR has been fully setup by the publishing strategy, this PR adds logic to ensure the replicas is set to the number of infra nodes so there is one router pod per infra node.

### CODE REVIEW

**Comment by fahlmant** [comment]
I had to add the `distinctNode` function because calling the List on the nodeList object was returning 6 of each infra node 

```
Node: 0 ip-10-0-180-206.ec2.internal infra
Node: 1 ip-10-0-221-126.ec2.internal infra
Node: 2 ip-10-0-138-56.ec2.internal infra
Node: 3 ip-10-0-221-126.ec2.internal infra
Node: 4 ip-10-0-180-206.ec2.internal infra
Node: 5 ip-10-0-138-56.ec2.internal infra
Node: 6 ip-10-0-180-206.ec2.internal infra
Node: 7 ip-10-0-221-126.ec2.internal infra
Node: 8 ip-10-0-138-56.ec2.internal infra
Node: 9 ip-10-0-221-126.ec2.internal infra
Node: 10 ip-10-0-180-206.ec2.internal infra
Node: 11 ip-10-0-138-56.ec2.internal infra
Node: 12 ip-10-0-180-206.ec2.internal infra
Node: 13 ip-10-0-221-126.ec2.internal infra
Node: 14 ip-10-0-138-56.ec2.internal infra
Node: 15 ip-10-0-138-56.ec2.internal infra
Node: 16 ip-10-0-221-126.ec2.internal infra
Node: 17 ip-10-0-180-206.ec2.internal infra
```

**Comment by sam-nguyen7** [comment]
/lgtm
let me know if you ever find out why that returns 6 of each infra node :)

**Pull request closed without merging**
