### PR TITLE
sshd: Explicitly make host keys group readable

### PR DESCRIPTION
**Pull request by mbarnes**
The sshd process runs as a non-root user within the pod, whereas the mounted host keys are owned by root.  We therefore depend on the key files being group-readable.  Set this read bit explicitly instead of depending on the security context to set it.

Normally group-readable private keys are forbidden by OpenSSH, but it turns out the server [does NOT apply its strict permission checks when a private key is owned by a different user than itself](https://github.com/openssh/openssh-portable/blob/9bb8a303ce05ff13fb421de991b495930be103c3/authfile.c#L96-L104).

### CODE REVIEW

**Comment by lisa** [comment]
@mbarnes What are the owner:group owner of the file inside the container expected to be?

**Review by mwoodson — APPROVED** [review]
/lgtm

**Review by georgettica — COMMENTED** [review]
If that was tested I can give a thumbs up
/approve

**Comment by mbarnes** [comment]
> If that was tested I can give a thumbs up

It was tested.  Used [BZ 1868976#c25](https://bugzilla.redhat.com/show_bug.cgi?id=1868976#c25) as a reproducer.

**Pull request merged**
