### PR TITLE
[WIP]disable controller when running on cluster >= 4.13

### PR DESCRIPTION
**Pull request by bmeng**
wrt [OSD-16007](https://issues.redhat.com//browse/OSD-16007)

### CODE REVIEW

**Comment by bmeng** [comment]
Tested on both 4.12 and 4.13 clusters. Works well.

**Comment by fahlmant** [comment]
Are we also deprecating api availability? This CR handles both Ingress and API availability

**Comment by bmeng** [comment]
That's good point, API endpoint was not considered, I will need to rework

**Comment by hectorakemp** [comment]
@bmeng probably time to close this?

**Pull request closed without merging**
