### PR TITLE
Remove everything SSHD related

### PR DESCRIPTION
**Pull request by fahlmant**
Related to https://issues.redhat.com//browse/OSD-11724 and https://github.com/openshift/managed-cluster-config/pull/1163

Hive is the only place we're still using SSHD. Since we're removing it from hive, this PR removes everything related from CIO deployments.

### CODE REVIEW

**Comment by fahlmant** [comment]
/hold

This needs to be synchronized with https://github.com/openshift/managed-cluster-config/pull/1163 to avoid the operator from erroring on existing clusters

**Comment by cblecker** [comment]
@fahlmant I think there are still some ssh references in `pkg/cloudclient/aws/private_test.go` and `pkg/testutils/testutils.go`. Would you mind having a look at thise?

**Pull request merged**
