### PR TITLE
Set external traffic policy for rh-api endpoint

### PR DESCRIPTION
**Pull request by cblecker**
Sets the `.spec.externalTrafficPolicy` for the rh-api load balancer to local. This ensures that rh-api traffic cannot route through a bad worker node, but instead will only pass healthchecks on the nodes that actually are hosting a healthy api server.

### CODE REVIEW

**Comment by cblecker** [comment]
/hold
This is ready for review, but I want to control when it merges.

**Review by boranx — COMMENTED** [review]
/lgtm

putting as a ref: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
Nice tweak! Feel free to unhold anytime when ready to merge

**Comment by cblecker** [comment]
I have tested the rollout of this on stage, and it was successful.

**Pull request merged**
