### PR TITLE
sdcicd-885 migrating e2e tests

### PR DESCRIPTION
**Pull request by ritmun**
[sdcicd-885](https://issues.redhat.com//browse/sdcicd-885)

Migrate more e2e tests from osde2e

Progress: 
- [x] apischeme_cr.go    (This PR)  ([link to  original tests)](https://github.com/openshift/osde2e/blob/main/pkg/e2e/operators/cloudingress/apischeme_cr.go)
- [x] upgrade.go  (This PR)        ([link to original](https://github.com/openshift/osde2e/blob/main/pkg/e2e/operators/cloudingress/upgrade.go))
- [x] installed.go    (This PR)   ([link to original](https://github.com/openshift/osde2e/blob/main/pkg/e2e/operators/cloudingress/installed.go))
- [x] rhapi_endpoint.go          (This PR) ([original test](https://github.com/openshift/osde2e/blob/main/pkg/e2e/operators/cloudingress/rhapi_endpoint.go))
- [x] rhapi_lb.go  (already migrated)        
- [ ] deletetapps2.go            
- [ ] public_private.go         
- [x] certificate.go    (deprecated; CIO no longer manages application ingress on 4.14+)         
- [ ] dnsname.go                 
- [ ] publishingstrategies_cr.go 
- [ ] routeSelector.go
- [x] cloudingress.go            (not a test)
- [ ] secondary_router.go

### CODE REVIEW

**Comment by AlexVulaj** [comment]
/lgtm

All tests pass locally for me.

**Review by fahlmant — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
