### PR TITLE
Update operator rbac permissions

### PR DESCRIPTION
**Pull request by sam-nguyen7**
- Remove permissions from cloud-ingress-operator clusterRole
- Add cloud-ingress-operator Role and necessary permissions

### CODE REVIEW

**Comment by robotmaxtron** [comment]
Deployed this to a fresh stage cluster, previously seen error messages around rbac seem to be cleared up.
/lgtm

**Review by fahlmant — COMMENTED** [review]
@sam-nguyen7 Why do the blocks for the cloudingress.managed.openshift.io apiGroup have *, then also apishemes and publishingstrategies explicitly listed?

**Comment by sam-nguyen7** [comment]
@boranx I believe you got this working while testing? Mind giving it lgtm label?

**Review by fahlmant — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
