### PR TITLE
Post-boilerplate cleanup

### PR DESCRIPTION
**Pull request by 2uasimojo**
Remove obsolete hack scripts and make targets

### CODE REVIEW

**Comment by jharrington22** [comment]
@2uasimojo I didn't remove the `generate_template.py` in #168 because I wanted to see if it was used else where. But it looks like its just a helper script. 

This is what added the CRDs to the Selector Sync Set in the first place.

Before we merge this I want to make sure all clusters get `v0.1.364-9a6ba79` first

**Comment by 2uasimojo** [comment]
> @2uasimojo I didn't remove the `generate_template.py` in #168 because I wanted to see if it was used else where. But it looks like its just a helper script.

I'm pretty sure the script relies on the [other resources you deleted in #164](https://github.com/openshift/cloud-ingress-operator/pull/164/files#diff-991950eb890e424406e645aab3e79b280998877aa3c97dfd8488bebdcf8cac19) so it was already dead. If it's still needed, we'll have to resurrect the whole shooting match anyway.

But yeah, there's nothing urgent about this PR -- I actually spun it up in case you needed something to merge yesterday to kick deploys :)

**Review by fahlmant — APPROVED** [review]
/hold cancel
/lgtm

**Review by fahlmant — APPROVED** [review]
/hold cancel
/lgtm

**Pull request merged**
