### PR TITLE
Remove legacy ingress feature flag label logic from cloud-ingress-operator

### PR DESCRIPTION
**Pull request by hectorakemp**
Makes it so that second ingresses can't be created on any version. Previously the behaviour was that it was blocked only if the feature flag was false (i.e the managed ingress v2 behaviour was active).

This PR keeps the default ingress 'ownership' transfer behaviour in [SDE-1768](https://issues.redhat.com/browse/SDE-1768) behind the `legacy-ingress-support: false` feature flag. This aligns with the behaviour of the ROSA/OCM CLI on prod.

### CODE REVIEW

**Comment by hectorakemp** [comment]
The logic here is quite complicated and hard to understand - so I am willing to reach out further or elaborate to anyone that has questions about this pull request.

**Review by boranx — APPROVED** [review]
/lgtm

Tested on a staging cluster whose version is 4.13.4
```shell
{"level":"info","ts":"2023-08-30T14:19:29+03:00","logger":"controller_publishingstrategy","msg":"Cluster using native OCP ingress management, remvoing cloud-ingress-operator ownership of default IngressController","Request.Namespace":"openshift-cloud-ingress-operator","Request.Name":"publishingstrategy"}
{"level":"info","ts":"2023-08-30T14:19:29+03:00","logger":"controller_publishingstrategy","msg":"IngressController default is being disowned by cloud-ingress-operator","Request.Namespace":"openshift-cloud-ingress-operator","Request.Name":"publishingstrategy"}
{"level":"info","ts":"2023-08-30T14:19:29+03:00","logger":"controller_publishingstrategy","msg":"IngressController default is being given cluster ingress finalizer","Request.Namespace":"openshift-cloud-ingress-operator","Request.Name":"publishingstrategy"}
{"level":"info","ts":"2023-08-30T14:19:29+03:00","logger":"controller_publishingstrategy","msg":"Exiting, version 4.13 or greater and using new native ingress feature","Request.Namespace":"openshift-cloud-ingress-operator","Request.Name":"publishingstrategy"}
```

**Pull request merged**
